import CanonicalLaneMathlibCore

namespace HautevilleHouse
namespace PlanetaryGeologyCanonicalLaneLean

open HautevilleHouse.CanonicalLaneMathlibCore

end PlanetaryGeologyCanonicalLaneLean
end HautevilleHouse
